# Generated by Django 3.1.5 on 2021-01-10 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=1)),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
            ],
        ),
    ]
