# Generated by Django 3.1.5 on 2021-01-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_query'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Feedback',
        ),
    ]
